name: dmorse_web
description: A simple web application to translate text to morse code.
version: 0.3.0
author: hkoktay <hknkoktay+github@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.11.0
  angular_router: ^2.0.0-alpha+22

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
  sass_builder: ^2.1.2
  pageloader: ^3.2.0
